### ISSUE TITLE
Alle data slettes når appen opdateres

### ISSUE THREAD

**Issue by Asbjoern** [nobio2009/Le-money-thingy#2]
Når appen opdateres med 'git pull', så overskrives alle data.

**Comment by nobio2009** [comment]
Done `def ensure_json_files_exist():
    files_to_check = {
        'static/buttons.json': [],
        'static/noa_buttons.json': [],
        'static/milo_buttons.json': [],
        'static/lauge_buttons.json': [],
        'static/balder_buttons.json': [],
        'balder_log.json': [],
        'counters.json': {'noa': 0, 'milo': 0, 'balder': 0, 'lauge': 0},
        'lauge_log.json': [],
        'milo_log.json': [],
        'noa_log.json': []
    }

    for file_path, default_content in files_to_check.items():
        if not os.path.exists(file_path):
            directory = os.path.dirname(file_path)
            if directory and not os.path.exists(directory):
                os.makedirs(directory)
                
            with open(file_path, 'w') as f:
                json.dump(default_content, f, indent=2)
            print(f"Created missing file: {file_path}")
        else:
            print(f"File exists: {file_path}")
    return True

try:
    noBrokeFiles = ensure_json_files_exist()
    if noBrokeFiles:
        app = Flask(__name__)

        # Paths to the JSON files
        COUNTER_FILE = 'counters.json'
        LOG_FILES = {
            'noa': 'noa_log.json',
            'milo': 'milo_log.json',
            'balder': 'balder_log.json',
            'lauge': 'lauge_log.json'
        }
        #The rest of the serverside code`
